### PR TITLE
introduce commonjs package manager support

### PR DESCRIPTION
**Pull request by venkateshsampath**
This patch is to allow use of commonjs package manager and es6 modules.
courtesy: https://github.com/angular-ui/ui-router
example:
import ngInputModified from 'angular-input-modified';
angular.module('foo', [ngInputModified]);

### CODE REVIEW

**Comment by venkateshsampath** [comment]
Hi @slavafomin & Team,

Thanks for this nice extension. It helped us to meet one of our requirements in our projects in a cleaner way. 
Since we were using webpack module bundler with es6 in our project, we were facing few problem in importing the ngInputModified module as it needs commonjs package manager support. 
Noticed a simple solution provided at angular-ui-router. Applied a similar fix for angular-input-modified too and submitting this PR.
Can you guys please review my changes and merge the patch if it looks ok. 
Request you to please publish a new npm package so that we could use it with webpack and es6.

**Comment by slavafomin** [comment]
Thank you @venkateshsampath! I will take a look at this. Sorry for a long delay.

**Comment by slavafomin** [comment]
Hello @venkateshsampath, could you please create a small project that requires `input-modified` and builds a bundle using webpack? Maybe add some integration tests to it too? Then I will be able to update our module to make it compatible with your build tools.

**Comment by slavafomin** [comment]
@venkateshsampath please see #37.

**Pull request closed without merging**
