### PR TITLE
Fix $dirty bug

### PR DESCRIPTION
**Pull request by brunowego**
Reported in https://github.com/betsol/angular-input-modified/issues/50

### CODE REVIEW

**Comment by brunowego** [comment]
Thanks for this great work @slavafomin! 👍

**Comment by slavafomin** [comment]
Thank you @brunowego for a pull-request.

However, could you please explain the edit?

**Comment by brunowego** [comment]
You have fixed. Thanks!

**Comment by slavafomin** [comment]
@brunowego thank you!

**Pull request closed without merging**
