### PR TITLE
Update form.js

### PR DESCRIPTION
**Pull request by zxyang**
When form's modified status changes, emit an event "$$formModifiedStateChanged". Parent scope can listen to this event.

### CODE REVIEW

**Comment by slavafomin** [comment]
Hello @zxyang! Thank you for a PR.

However, could you please give a practical example of where this can be used?

Also, I have the following question:

1. Why do you use `$$` prefix? If I'm correct the `$` prefix is for Angular core modules and `$$` is for a non-public API.

2. I think you should pass an object as an event data containing name of the form and a reference to the `ngForm` instance for convenience of the end user.

3. Will you be able to also update the docs?

Thanks!

**Comment by zxyang** [comment]
Sure， will make changes. What name do you suggest?

I have an email like app, I want to highlight the list item if its content has changed.

Regards,
Zibin

-----Original Message-----

**Comment by slavafomin** [comment]
Maybe `inputModified.formChanged`?

**Comment by zxyang** [comment]
Sounds good!

-----Original Message-----

**Comment by zxyang** [comment]
will have a new pull request

**Pull request closed without merging**
