### PR TITLE
Watching another possible ng-models which are using a div-container

### PR DESCRIPTION
**Pull request by andywunderlich**
i.e. ui-select

### CODE REVIEW

**Comment by slavafomin** [comment]
Hello @andywunderlich!

Thank you for your interest in this module and your PR.

However, I'm not sure we should attach this directive to every possible element. HTML standard and AngularJS in particular provides were specific list of supported form elements. They are: `input`, `select`, `textarea` and `form` itself. If we would provide directive for every custom control that are not part of HTML standard, we will have to make sure that our directive works correctly with them. This is a considerable amount of work for module maintainers and I don't have such resources.

Maybe the better approach will be to attach this directive by `ngModel` attribute. We can then rely on a common standard of `ngModel` supported by AngularJS itself. I think I will test this approach in a separate branch of the repo. Will you be able to test it with some custom form elements (like `ui-select` that you have mentioned)?

Thanks!

**Comment by slavafomin** [comment]
I've just pushed a `feat-alt-attach` branch. Could you check it please and verify if it solves the problem? Will you be able to add another demo for `ui-select` also please? You can just copy main demo and change it according to your needs. You can add library to the page by means of RawGit.

**Comment by andywunderlich** [comment]
Hello Slava,

thank you for taking your time and refactoring your code. I've tested it and what can i say, it works now very well in my forms! Fantastic :+1: I'll add an another demo with ui-select.

Andy

**Comment by slavafomin** [comment]
Okay, thanks! You can push your demo to the mentioned branch and create a PR. I will merge it and create a new release.

**Pull request closed without merging**
